version: "3.8"

services:
  server:
    container_name: server
    build: server
    ports:
      - "9999:5000"
    environment:
      - "PORT=5000"
      - "FOLDER=/server/local"
  client1:
    build: client
    environment:
      - "SERVER_PORT=5000"
      - "SERVER_HOST=server"
    depends_on:
      - server
  client2:
    build: client
    environment:
      - "SERVER_PORT=5000"
      - "SERVER_HOST=server"
      - "FREEZE_EARLY=1"
    depends_on:
      - server
  client3:
    build: client
    environment:
      - "SERVER_PORT=5000"
      - "SERVER_HOST=server"
      - "FREEZE_LATE=1"
    depends_on:
      - server
  client4:
    build: client
    environment:
      - "SERVER_PORT=5000"
      - "SERVER_HOST=server"
      - "TOTAL_MESSAGES=10"
    depends_on:
      - server
